apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "marcorezende/spark-delta-aws:3.5.0-custom"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///tmp/spark.py"
  sparkVersion: "3.5.0"
  sparkUIOptions:
    serviceLabels:
      test-label/v1: 'true'
    servicePort: 4040
    servicePortName: "ui"
    serviceType: "ClusterIP"
  restartPolicy:
    type: Never

  driver:
    cores: 2
    coreLimit: "6"
    memory: "8g"
    env:
      - name: "ITERATOR"
        value: "3"
      - name: "SCALE_FACTOR"
        value: "50"
    labels:
      version: 3.5.0
    serviceAccount: spark
    volumeMounts:
      - name: spark-app-volume
        mountPath: /tmp

  executor:
    cores: 2
    instances: 2
    memory: "8g"
    env:
      - name: "ITERATOR"
        value: "3"
      - name: "SCALE_FACTOR"
        value: "50"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: spark-app-volume
        mountPath: /tmp

  volumes:
    - name: spark-app-volume
      hostPath:
        path: "/run/desktop/mnt/host/c/Users/edierley.messias/Desktop/testedockergpu/sparkOnKubernetes"
        type: Directory